app:
  name: "Adult_Census_income_prediction"
  version: "1.0.0"
  description: "A system to predict income is more than 50k or not"

server:
  host: "0.0.0.0"      
  port: 8000           
  debug: true          

logging:
  level: "INFO"        
  file: "logs/app.log" 
  format: "[%(asctime)s] %(levelname)s - %(message)s"

environment:
  mode: "development"  
