astra:
  client_id: "AstraCS:sbeWsJFERlmIzFzvFdPYbGHb:d1ca01f2af290a02c33960b0a3044099033ed0cada776a51989f9379329f0f3a"
  api_endpoint: "https://84f4acd1-8998-472f-9808-f8e64f9bb435-us-east1.apps.astra.datastax.com"
  collection_name: "adult_census_income_prediction"
